springboot_owner: "{{ansible_user}}"
springboot_vm_options: '-XX:MaxRAM=768M -XX:MinRAMPercentage=30 -XX:MaxRAMPercentage=50'
springboot_profiles_active: 'prod'
springboot_app_options: ''
springboot_jmxport: 15980

## full list of vars
#   springboot_name: 'kaif-web'
#   springboot_owner: "{{ansible_user}}"
#   springboot_vm_options: '-Xmx512M -Xms512M'
#   springboot_profiles_active: 'prod'
#   springboot_app_options" '-Dfoo=bar'
