name: kaif_web
description: Kaif Web
environment:
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  intl: any
  less_dart: ">=2.3.7 <3.0.0"
dev_dependencies:
  webdev: ^2.5.6
  build_runner: ^1.8.1
  build_web_compilers: ^2.9.0
