name: kaif_web
description: Kaif Web
environment:
  #TODO#dart2 use latest dart2
  sdk: '>=2.0.0 <3.0.0'
dependencies:
  #TODO#dart2 barback i18n
  #barback: any
  intl: any
  #TODO#dart2 cookie
  #cookie: ">=0.0.4 <0.1.0"
  #TODO#dart2 upgrade less
  less_dart: "2.1.0"
dev_dependencies:
  webdev: any
  build_runner: ">=0.8.10 <2.0.0"
  build_web_compilers: ">=0.3.6 <2.0.0"

  #TODO#dart2 unit test
  #unittest: any
transformers:
  - less_dart:
      entry_points:
        - web/less/kaif.less
      output: web/css/kaif.css
      include_path: web/less
      cleancss: true
      compress: true
  - kaif_web:
      $include: ["lib/intl/messages*.dart", "lib/i18n_link/messages*.properties"]
  - $dart2js:
      commandLineOptions: [--show-package-warnings]
