name: kaif_web
description: Kaif Web
dependencies:
  browser: any
  barback: any
  intl: any
  cookie: ">=0.0.4 <0.1.0"
  less_dart: "1.0.0"
dev_dependencies:
  unittest: any
transformers:
  - less_dart:
      entry_points:
        - web/less_link/kaif.less
      output: web/css/kaif.css
      include_path: web/less_link
      cleancss: true
      compress: true
  - kaif_web:
      $include: ["lib/intl/messages*.dart", "lib/i18n_link/messages*.properties"]
  - $dart2js:
      commandLineOptions: [--show-package-warnings]
