# this should change in production, by a secret file that not commit to git

inv_catalina_opts: >
                   -Denv.dbpassword=changeme
                   -Denv.account.mac=n7LOo9kKqSqM-fshf_T3xw
                   -Denv.account.key=dnXAz2u6mn4L_vZyiW0hHA
                   -Denv.oauth.mac=n7LOo9kKqSqM-fshf_T3xw
                   -Denv.oauth.key=dnXAz2u6mn4L_vZyiW0hHA
                   -Denv.mail.aws-secret-key=false
                   -Denv.mail.aws-access-key=false

inv_nginx_dhparam_pem_content: |
                               -----BEGIN DH PARAMETERS-----
                               MIICCAKCAgEAiN7aXhGrIx7cDz3o6yVprfAjNjahyAPUW2Ssc61QylewVMWwzJf0
                               8oS+gafU+PI8myS/DOz2K6byJ57VLOpFUAmHpkN++DCTXZIeGDzCqYYDe8Juz/tx
                               c+vCtuIOLntcF68lRlxi8aPm1ZdK+LNJ5jk4L1rFb8piKOkvbvT+UC7Khgmnu5SI
                               J4Eal1uFlAFf+MiKZSMQZ9Edggj1uktgXbspGW0EWsmiY2T1LqpWr1OcdgmmK4fQ
                               fO+AZ6WqNUTsODrHm3usk1qD040aWGgZFAg1Xj/f+Au/rwTSgwxeMHYOqvLYGAyO
                               l7YIG0i7wKwoMrkJF3A73gQ12xWArUz6pQLGBt/J0ZbFsjV1FQrNTlxARyVFIMet
                               UsQjRHbyTbYhuHWrJx4yio1WxeN/RnvvW3hBwhwEXgvbYWoBwRvDhQ86kK3siOXm
                               ydDbgnKlxweSbiH6vp37tw+nc1o75vl7ga+pXdp+Jr0cPXIOZHftpaSZay/519kw
                               ZY1sxIdmYS8DKC2ODW4IJu/SymoUh0xldJUgt0kMppfEED4enFRTLknHLBZoO2vO
                               2cZhBPK7yWY7uRTdgkUWMy6RUJdBdjcSSfp4VHcwnVHP4bHeyXgxvgxExnBx7jtO
                               33lPJHA8ppGwnpOMOtbxLtIfGNLUq4nA5MRRmgsY/lmTRVyzMlHAuxsCAQI=
                               -----END DH PARAMETERS-----

inv_nginx_ssl_crt_content: |
                           -----BEGIN CERTIFICATE-----
                           MIIC+zCCAeOgAwIBAgIJAJPe3OwrOq6bMA0GCSqGSIb3DQEBBQUAMBQxEjAQBgNV
                           BAMMCSoua2FpZi5pbzAeFw0xNTAxMTYxNDI1MTJaFw0yNTAxMTMxNDI1MTJaMBQx
                           EjAQBgNVBAMMCSoua2FpZi5pbzCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoC
                           ggEBAMh8Kbqvg/vOPPjT+EtRWVWACA67Q9POKzyKanhSrUTZmphKKuzD/mNyvtur
                           B1bYwpgVYJmFDjfcbJZkg7V/sPREKGapU1LA6yVHl7UodKsOrKWk/SbRGSN+2W5J
                           NrZvjxNMjgF7DKXgGCHWSNPC/D3SeK72Z/BQIQHC50nfQVOhS25pCH1VQkL0v9++
                           cCBcmEAaj6gZQnQf8Wp3a+E6lkEkRNZS64VSDbyrXYUToROt6FaTsXZocLYAecbB
                           U6OAT20o8rzdm/XWr8QksBI1jOpA3Iu2kqFdt/78Pr2CwlsqGT4pa1a8MzADo0Ur
                           Q/OBtn1ICfk7J29QH1a/tGZwbpECAwEAAaNQME4wHQYDVR0OBBYEFMbrNCP0knuE
                           2Ah4qa1q6BlFs9raMB8GA1UdIwQYMBaAFMbrNCP0knuE2Ah4qa1q6BlFs9raMAwG
                           A1UdEwQFMAMBAf8wDQYJKoZIhvcNAQEFBQADggEBACk8OwuK2lbEQeFb/sKT2auY
                           L60EOC95AqNEh3MsXvIl4mYphrRFC2z2s9+FWMFZwgO/VJDy0SY4ChLMwrTY93a+
                           tYl01wVAOUe/8Ie9jUgn387zCgq+ZdY+Ym+zSXZqR6NVG/EyK2akZ+glt93P0i0Y
                           tOmrgfyApYer/iw8BbrE54lmf/s1CcGJAj+lWHAhiepghKwz0S3l1W/zUGiAJ5KH
                           8JQu0O57h18gJCLFrkTjVdCmSjkU5b6ur/7SQSBINe5Xx3Uwouhu3klRWSNFELYO
                           2O4Fr5pFy1hvf8u1RommGeEi7nFz3WuW+DpdK9Z4yJHLRiy5iW2w7uUmxsK4CDQ=
                           -----END CERTIFICATE-----
                           -----BEGIN CERTIFICATE-----
                           MIIE0DCCA7igAwIBAgIBBzANBgkqhkiG9w0BAQsFADCBgzELMAkGA1UEBhMCVVMx
                           EDAOBgNVBAgTB0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoT
                           EUdvRGFkZHkuY29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRp
                           ZmljYXRlIEF1dGhvcml0eSAtIEcyMB4XDTExMDUwMzA3MDAwMFoXDTMxMDUwMzA3
                           MDAwMFowgbQxCzAJBgNVBAYTAlVTMRAwDgYDVQQIEwdBcml6b25hMRMwEQYDVQQH
                           EwpTY290dHNkYWxlMRowGAYDVQQKExFHb0RhZGR5LmNvbSwgSW5jLjEtMCsGA1UE
                           CxMkaHR0cDovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkvMTMwMQYDVQQD
                           EypHbyBEYWRkeSBTZWN1cmUgQ2VydGlmaWNhdGUgQXV0aG9yaXR5IC0gRzIwggEi
                           MA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC54MsQ1K92vdSTYuswZLiBCGzD
                           BNliF44v/z5lz4/OYuY8UhzaFkVLVat4a2ODYpDOD2lsmcgaFItMzEUz6ojcnqOv
                           K/6AYZ15V8TPLvQ/MDxdR/yaFrzDN5ZBUY4RS1T4KL7QjL7wMDge87Am+GZHY23e
                           cSZHjzhHU9FGHbTj3ADqRay9vHHZqm8A29vNMDp5T19MR/gd71vCxJ1gO7GyQ5HY
                           pDNO6rPWJ0+tJYqlxvTV0KaudAVkV4i1RFXULSo6Pvi4vekyCgKUZMQWOlDxSq7n
                           eTOvDCAHf+jfBDnCaQJsY1L6d8EbyHSHyLmTGFBUNUtpTrw700kuH9zB0lL7AgMB
                           AAGjggEaMIIBFjAPBgNVHRMBAf8EBTADAQH/MA4GA1UdDwEB/wQEAwIBBjAdBgNV
                           HQ4EFgQUQMK9J47MNIMwojPX+2yz8LQsgM4wHwYDVR0jBBgwFoAUOpqFBxBnKLbv
                           9r0FQW4gwZTaD94wNAYIKwYBBQUHAQEEKDAmMCQGCCsGAQUFBzABhhhodHRwOi8v
                           b2NzcC5nb2RhZGR5LmNvbS8wNQYDVR0fBC4wLDAqoCigJoYkaHR0cDovL2NybC5n
                           b2RhZGR5LmNvbS9nZHJvb3QtZzIuY3JsMEYGA1UdIAQ/MD0wOwYEVR0gADAzMDEG
                           CCsGAQUFBwIBFiVodHRwczovL2NlcnRzLmdvZGFkZHkuY29tL3JlcG9zaXRvcnkv
                           MA0GCSqGSIb3DQEBCwUAA4IBAQAIfmyTEMg4uJapkEv/oV9PBO9sPpyIBslQj6Zz
                           91cxG7685C/b+LrTW+C05+Z5Yg4MotdqY3MxtfWoSKQ7CC2iXZDXtHwlTxFWMMS2
                           RJ17LJ3lXubvDGGqv+QqG+6EnriDfcFDzkSnE3ANkR/0yBOtg2DZ2HKocyQetawi
                           DsoXiWJYRBuriSUBAA/NxBti21G00w9RKpv0vHP8ds42pM3Z2Czqrpv1KrKQ0U11
                           GIo/ikGQI31bS/6kA1ibRrLDYGCD+H1QQc7CoZDDu+8CL9IVVO5EFdkKrqeKM+2x
                           LXY2JtwE65/3YR8V3Idv7kaWKK2hJn0KCacuBKONvPi8BDAB
                           -----END CERTIFICATE-----
                           -----BEGIN CERTIFICATE-----
                           MIIEfTCCA2WgAwIBAgIDG+cVMA0GCSqGSIb3DQEBCwUAMGMxCzAJBgNVBAYTAlVT
                           MSEwHwYDVQQKExhUaGUgR28gRGFkZHkgR3JvdXAsIEluYy4xMTAvBgNVBAsTKEdv
                           IERhZGR5IENsYXNzIDIgQ2VydGlmaWNhdGlvbiBBdXRob3JpdHkwHhcNMTQwMTAx
                           MDcwMDAwWhcNMzEwNTMwMDcwMDAwWjCBgzELMAkGA1UEBhMCVVMxEDAOBgNVBAgT
                           B0FyaXpvbmExEzARBgNVBAcTClNjb3R0c2RhbGUxGjAYBgNVBAoTEUdvRGFkZHku
                           Y29tLCBJbmMuMTEwLwYDVQQDEyhHbyBEYWRkeSBSb290IENlcnRpZmljYXRlIEF1
                           dGhvcml0eSAtIEcyMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAv3Fi
                           CPH6WTT3G8kYo/eASVjpIoMTpsUgQwE7hPHmhUmfJ+r2hBtOoLTbcJjHMgGxBT4H
                           Tu70+k8vWTAi56sZVmvigAf88xZ1gDlRe+X5NbZ0TqmNghPktj+pA4P6or6KFWp/
                           3gvDthkUBcrqw6gElDtGfDIN8wBmIsiNaW02jBEYt9OyHGC0OPoCjM7T3UYH3go+
                           6118yHz7sCtTpJJiaVElBWEaRIGMLKlDliPfrDqBmg4pxRyp6V0etp6eMAo5zvGI
                           gPtLXcwy7IViQyU0AlYnAZG0O3AqP26x6JyIAX2f1PnbU21gnb8s51iruF9G/M7E
                           GwM8CetJMVxpRrPgRwIDAQABo4IBFzCCARMwDwYDVR0TAQH/BAUwAwEB/zAOBgNV
                           HQ8BAf8EBAMCAQYwHQYDVR0OBBYEFDqahQcQZyi27/a9BUFuIMGU2g/eMB8GA1Ud
                           IwQYMBaAFNLEsNKR1EwRcbNhyz2h/t2oatTjMDQGCCsGAQUFBwEBBCgwJjAkBggr
                           BgEFBQcwAYYYaHR0cDovL29jc3AuZ29kYWRkeS5jb20vMDIGA1UdHwQrMCkwJ6Al
                           oCOGIWh0dHA6Ly9jcmwuZ29kYWRkeS5jb20vZ2Ryb290LmNybDBGBgNVHSAEPzA9
                           MDsGBFUdIAAwMzAxBggrBgEFBQcCARYlaHR0cHM6Ly9jZXJ0cy5nb2RhZGR5LmNv
                           bS9yZXBvc2l0b3J5LzANBgkqhkiG9w0BAQsFAAOCAQEAWQtTvZKGEacke+1bMc8d
                           H2xwxbhuvk679r6XUOEwf7ooXGKUwuN+M/f7QnaF25UcjCJYdQkMiGVnOQoWCcWg
                           OJekxSOTP7QYpgEGRJHjp2kntFolfzq3Ms3dhP8qOCkzpN1nsoX+oYggHFCJyNwq
                           9kIDN0zmiN/VryTyscPfzLXs4Jlet0lUIDyUGAzHHFIYSaRt4bNYC8nY7NmuHDKO
                           KHAN4v6mF56ED71XcLNa6R+ghlO773z/aQvgSMO3kwvIClTErF0UZzdsyqUvMQg3
                           qm5vjLyb4lddJIGvl5echK1srDdMZvNhkREg5L4wn3qkKQmw4TRfZHcYQFHfjDCm
                           rw==
                           -----END CERTIFICATE-----

inv_nginx_ssl_key_content: |
                           -----BEGIN RSA PRIVATE KEY-----
                           MIIEpAIBAAKCAQEAyHwpuq+D+848+NP4S1FZVYAIDrtD084rPIpqeFKtRNmamEoq
                           7MP+Y3K+26sHVtjCmBVgmYUON9xslmSDtX+w9EQoZqlTUsDrJUeXtSh0qw6spaT9
                           JtEZI37Zbkk2tm+PE0yOAXsMpeAYIdZI08L8PdJ4rvZn8FAhAcLnSd9BU6FLbmkI
                           fVVCQvS/375wIFyYQBqPqBlCdB/xandr4TqWQSRE1lLrhVINvKtdhROhE63oVpOx
                           dmhwtgB5xsFTo4BPbSjyvN2b9davxCSwEjWM6kDci7aSoV23/vw+vYLCWyoZPilr
                           VrwzMAOjRStD84G2fUgJ+Tsnb1AfVr+0ZnBukQIDAQABAoIBAFR+6ANzV7f3uwDQ
                           LZRoy7LaTAsRZ8vL17MjTy45AifDYoGOuLqi/AMj6EaitWwn3RPF5rmtN0nZz7Yu
                           1MfY8lZwp2plMOXuwuwqWUkTrOAvRhpmB/+lHugz3SW7G6EWMYHbwPnkx3bdlK4m
                           JvmA81iG7TAoT7QbwV2BrIMY4eqBkDsNLNBTRaugeJx9cAq1YzDedsLXeoyUnIyc
                           Eum6/Tf5RJARuM6yfhF+q3CZXhGvYUifUrVDRXHFIy1uygkhhS77vvxsNOKz778Y
                           dTYkR5QMbhs7I3HiZlAlHBwkqHQIjxAOfIDsPoAhJDWlHcwawaw22iHfw822j9KY
                           sLN3BgECgYEA6mVmKGmg8SYVscIAsSqGeD6SaWesvecxPt8v0pxR6MdyYY/bz6YB
                           lTUagaBlHk9MBnhu/HpkNasZOoTA4CclVU8XzwStuKWtIXBA0Mb3XblbO6o+mQI9
                           Rd4vOkO8JPc7yVIBpDYWgw6sUEfwdrfmFsM6axa1qnMCO42r3CjpGCECgYEA2vag
                           35mCmgcLClNnfXgUe6+MLOArlvKTlFiKB3PhsJcBi0BAu5uWiDrtumBn+Qe/4bzr
                           jjWsxK+WJl37rHC1kAS4AagpDek/qB8A1Ta1hDTHw7bVCCwxHh/XoJkYeexjXF02
                           46bO7/UnMzELuU3ORJ6a2RLnKSF3f+GBCCpTyHECgYBOA+PlrYqg2PE9kfnS/fl1
                           yjXHGXe4WVvdtkFfkyH8HW4npM8fpPw/4kXpQS6G0RPXz3v5Uu9JoaIrBQaBVOYr
                           J8Ef6Um8/H/McmVQV/j7W/dOu5JMMR+dwp7rgKH9l8BxeHcNZedGRbr6mYcirIDL
                           sL0f6ZYbnl3u3m+GPqOeoQKBgQCCLmdvCSGw2ccimHvLCP2Em9ZHR/Aiio5bgFhw
                           HeFs0BrG46iY4eQZko+MY4ztbkISv/N8VUUmmw42OWJMH6aSvXt44LWn46lJF0Wz
                           fhdlRswN/EGj3kJFmsDkZqE6u+RHIdRkfORDngl0UhCaVzvvaCzAKpDsz0zw5u2E
                           IUY2wQKBgQDiBPdq9wBjYK3G1v7VIHdxiA4Ad/Jbfk8OfAZAcJUGcjB9brKK07Ni
                           wOXhDV+a5MmcQpYSwtrcaq7NI0ilNOqidX59fD2DbtxqzbdP63F6Q5MWaM2McRU9
                           UNUUjdPzc7icx+jbRfBs7WZvSvbegYu36WUF990IqnQnM0AP4ek8vg==
                           -----END RSA PRIVATE KEY-----