---
##
#
# decrypt secret file before process production nodes
#
#
- hosts: localhost
  vars:
    private_key_content: "{{lookup('file', '../secret/kaif_rsa.vault')}}"
    pub_key_content: "{{lookup('file', '../secret/kaif_rsa.pub.vault')}}"

  tasks:
  - name: copy deployment private key
    copy:
      content: "{{private_key_content}}"
      dest: "../secret/kaif_rsa"
      mode: 0600
    no_log: true

  - name: copy deployment pub key
    copy:
      content: "{{pub_key_content}}"
      dest: "../secret/kaif_rsa.pub"
      mode: 0600
    no_log: true
