- hosts: pgs
  tasks:

  - name: copy schema files
    copy: src=db dest=/tmp force=yes
    sudo_user: postgres
    sudo: yes

  - name: stop kaif-web before drop database
    command: /usr/sbin/service kaif-web stop
    ignore_errors: yes
    sudo: yes

  - name: destroy and recreate database and schema
    shell: "{{ item }}"
    with_items:
      - psql < /tmp/db/recreate_db.sql
      - psql -U kaif < /tmp/db/schema.sql
      - psql < /tmp/db/recreate_db_ci.sql
    sudo_user: postgres
    sudo: yes

