---

- name: prepare certification directory
  file: path={{selfsigned_nginx_pki_path}}/{{item}} state=directory
  with_items:
    "{{selfsigned_domain_names}}"

- name: install dhparam
  command: openssl dhparam -out {{selfsigned_nginx_pki_path}}/{{item}}/dhparam.pem 2048
  args:
    creates: "{{selfsigned_nginx_pki_path}}/{{item}}/dhparam.pem"
  with_items:
    "{{selfsigned_domain_names}}"
  notify:
   - reload nginx

- name: Copy SSL certification
  copy:
    content: "{{selfsigned_ssl_crt_content}}"
    dest: "{{selfsigned_nginx_pki_path}}/{{item}}/letsencrypt-cert.pem"
  with_items:
    "{{selfsigned_domain_names}}"
  notify:
   - reload nginx

- name: Copy SSL certification chain
  copy:
    content: "{{selfsigned_ssl_chain_content}}"
    dest: "{{selfsigned_nginx_pki_path}}/{{item}}/letsencrypt-chain.pem"
  with_items:
    "{{selfsigned_domain_names}}"
  notify:
   - reload nginx

- name: Copy SSL private key
  copy:
    content: "{{ selfsigned_ssl_key_content }}"
    dest: "{{selfsigned_nginx_pki_path}}/{{item}}/letsencrypt-key.pem"
    owner: "{{nginx_user}}"
    group: "{{nginx_group}}"
    mode: 0600
  with_items:
    "{{selfsigned_domain_names}}"
  notify:
   - reload nginx

