---

##
## Ubuntu >= 16.04 (xenial) does not pre-install python 2 and aptitude, which require by ansible
## until ansible upgrade related module, we have to ensure install them manually.
##
- hosts: all
  gather_facts: false
  tasks:
    - name: ensure python 2, aptitude installed for ansible
      raw: apt install python aptitude -y -q
      become: true

- hosts: all
  roles:
    - role: common
      become: true

    - role: ohmyzsh
      become: true

- hosts: backup
  roles:
    - role: backup   #note that backup role do not use sudo