- name: update tzdata
  command: /usr/sbin/dpkg-reconfigure --frontend noninteractive tzdata

- name: reload ssh
  service: name=ssh state=reloaded

- name: restart ntp
  service: name=ntp state=restarted

- name: restart cron
  service: name=cron state=restarted

- name: reload sysctl

  ## command line way:
  #command: /sbin/sysctl -p

  ## service way:
  service: name=procps state=restarted
