## web server
server:
    port: 5980

## freemarker
spring.freemarker.cache: true

## actuator
management.context-path: /actuate

## database
spring.datasource.initialize: false
spring.datasource.schema: db
spring.datasource.data: db

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://192.168.59.59:5432/kaif
spring.datasource.username: kaif
spring.datasource.password: changeme
