## freemarker
spring.freemarker.cache: true

## actuator
management.context-path: /actuate

## database
spring.datasource.initialize: false
spring.datasource.schema: db
spring.datasource.data: db

---
spring:
    profiles: dev

spring.freemarker.cache: false

---
spring:
    profiles: test

spring.datasource.initialize: true