## web server
server:
    port: 5980


## freemarker
spring.freemarker:
    templateLoaderPath: /WEB-INF/views,classpath:/mail
    cache: true
    settings:
        show_error_tips: false


## spring mvc resources
# cache one month for css, js, favicon.ico...etc
spring.resources.cache-period: 2592000


## actuator
endpoints.enabled: false


## database
spring.datasource:
    initialize: false
    # TODO change `localhost` from ansible
    url: jdbc:postgresql://localhost:5432/kaif
    username: kaif
    password: ${dbpassword}
    schema:
    data:

## jmx


## messages


## mail
spring.mail.host: localhost


## model
account:
    mac: ${accountmac}
    key: ${accountkey}


## flake node id, every web server should use it's own unique node id
flake.node-id: ${flake.node-id}


## app, replace while gradle build (by ant syntax)
app.build: @app.build@


## logback
logging.config: classpath:logback-prod.xml


## misc
spring.main.show_banner: true