spring:
    profiles:
        active: dev

## freemarker
spring.freemarker.cache: false


## actuator
endpoints.enabled: true


## database


## jmx


## messages
spring.messages.cache-seconds: 0


## mail
spring.mail.host: 192.168.59.59


## model


## flake node id


## app


## logback
logging.config: classpath:logback-dev.xml