####
# Common properties for all profiles.
#
# If some properties are different between profiles, write property in each .yml
# Please do not write default value here and overwrite in specific .yml
####

## web server


## freemarker
spring.freemarker:
    # expose `request` so it is accessible in ftl
    request-context-attribute: request
    settings:
        datetime_format: yyyy-MM-dd
        number_format: 0.######

error.whitelabel.enabled: false


## spring mvc resources


## actuator
management.context-path: /actuate
endpoints.info.enabled: true
endpoints.health.enabled: true


## database
spring.datasource:
    driver-class-name: org.postgresql.Driver


## jmx
spring.jmx.enabled: false


## messages
spring.messages.basename: i18n/messages


## mail, see MailProperties.java
mail.sender-address: noreply@kaif.io
mail.sender-name: Kaif.io

mail.aws-sender-address:
mail.aws-secret-key:
mail.aws-access-key:


## model


## flake node id


## app


## logback


## misc
