spring:
    profiles:
        active: prod

## freemarker


## actuator


## database
spring.datasource.password: ${dbpassword}
spring.datasource.url: jdbc:postgresql://localhost:5432/kaif

## jmx


## messages


## mail
spring.mail.host: localhost


## model
account:
    mac: ${accountmac}
    key: ${accountkey}


## flake node id, every web server should use it's own unique node id
flake.node-id: ${flake.node-id}


## app, replace while gradle build (by ant syntax)
app.build: @app.build@


## logback
logging.config: classpath:logback-prod.xml
