## web server
server:
    port: 5980


## freemarker
spring.freemarker:
    cache: false
    settings:
        show_error_tips: true


## spring mvc resources
http.mappers.jsonPrettyPrint: true


## actuator
endpoints.enabled: true


## database
spring.datasource:
    initialize: false
    url: jdbc:postgresql://192.168.59.59:5432/kaif
    username: kaif
    password: changeme
    schema:
    data:

## jmx


## messages
spring.messages.cache-seconds: 0


## mail
spring.mail.host: 192.168.59.59


## model, see AccountSecret.java
account:
    mac: n7LOo9kKqSqM-fshf_T3xw
    key: dnXAz2u6mn4L_vZyiW0hHA

## oauth, see OauthSecret.java
oauth:
    mac: n7LOo9kKqSqM-fshf_T3xw
    key: dnXAz2u6mn4L_vZyiW0hHA

## flake node id
flake.node-id: 99


## app


## logback
logging.config: classpath:logback-dev.xml


## misc
spring.main.show_banner: true