## web server
server:
    port: 5980

## freemarker
spring.freemarker.cache: true
spring.freemarker.templateLoaderPath: /WEB-INF/views,classpath:/mail
spring.freemarker.settings.datetime_format: yyyy-MM-dd
spring.freemarker.settings.number_format: 0.######
# expose `request` so it is accessible in ftl
spring.freemarker.request-context-attribute: request
error.whitelabel.enabled: false

## actuator
management.context-path: /actuate
endpoints.enabled: false
endpoints.info.enabled: true
endpoints.health.enabled: true


## database
spring.datasource.initialize: false

spring.datasource.driver-class-name: org.postgresql.Driver
spring.datasource.url: jdbc:postgresql://192.168.59.59:5432/kaif
spring.datasource.username: kaif
spring.datasource.password: changeme


## jmx
spring.jmx.enabled: false


## messages
spring.messages.basename: i18n/messages


## mail, see MailProperties.java
mail.sender-address: noreply@kaif.io
mail.sender-name: Kaif.io

mail.aws-sender-address:
mail.aws-secret-key:
mail.aws-access-key:


## model, see AccountSecret.java
account:
    mac: n7LOo9kKqSqM-fshf_T3xw
    key: dnXAz2u6mn4L_vZyiW0hHA


## flake node id
flake.node-id: 99


## logback