---
- name: install python-pycurl
  apt: name=python-pycurl state=present update_cache=yes cache_valid_time=86400

- include: openjdk.yml
  when: java_versions is defined and java_versions is sequence
