---
# The variables file used for Postfix playbooks.
# If not overriden in inventory or as a parameter, this is the value that will be used

# no default value for postfix_hostname
# postfix_hostname: ''
postfix_domain: ''
postfix_notify_email: false
postfix_relayhost: ''
postfix_use_smtp: false
postfix_relayhost_user: false
postfix_relayhost_pass: false

# custom by ingram
postfix_inet_interfaces: 'loopback-only'
postfix_additional_my_networks: ''
postfix_header_size_limit: '102400'
postfix_smtp_tls_security_level: ''